### ISSUE TITLE
Complex JuMP variables

### ISSUE THREAD

**Issue by blegat** [jump-dev/ComplexOptInterface.jl#13]
```julia
@variable(model, x in COI.ComplexSpace())
```
should return `x_r + im x_i` where `x_r` and `x_i` are two real variables.

cc @ccoffrin

**Comment by ccoffrin** [comment]
For this type of case, what ways might I be able to specify starting points and bounds? Will both accept a complex value?

Here is an example of the kind of real expressions I would like to generalize.  `vr` is the real part and `vi` is the imag part.
```
@variable(model, -ref[:bus][i]["vmax"] <= vr[i in keys(ref[:bus])] <= ref[:bus][i]["vmax"], start=1.0)
@variable(model, -ref[:bus][i]["vmax"] <= vi[i in keys(ref[:bus])] <= ref[:bus][i]["vmax"], start=0.0)
```

**Comment by blegat** [comment]
Yes, this is already supported by the `@variable` syntax for `HermitianPSDCone`, you would do
```julia
@variable(model, x in COI.ComplexSpace(), start = sr + si * im, lower_bound = lbr + lbi * im, upper_bound = ubr * ubi * im)
```
which would be equivalent to
```julia
@variable(model, lbr <= xr <= ubr, start = sr)
@variable(model, lbi <= xi <= ubi, start = si)
x = xr + xi * im
```

**Comment by ccoffrin** [comment]
Perfect!
