### ISSUE TITLE
Unupdated version in the general registry

### ISSUE THREAD

**Issue by cgois** [jump-dev/ComplexOptInterface.jl#16]
Installation via Pkg currently set up version 0.0.2. Is an updated version going to the package registry soon, or should I manually install ComplexOptInterface for the time being? Thanks (:

**Comment by blegat** [comment]
You can see in
https://github.com/JuliaRegistries/General/blob/master/C/ComplexOptInterface/Compat.toml
that the version 0.0.3 requires MutableArithmetics v0.3 and MathOptInterface v0.10
You probably have a package that hasn't been updated yet that prevents ComplexOptInterface to be updated
Try doing `] add ComplexOptInterface@0.0.3` and you should see which one it is.

**Comment by cgois** [comment]
Everything works now (new to Julia, sorry). The package will certainly be extremely helpful to the quantum information optimization community (:

**Comment by blegat** [comment]
No worry, don't hesitate to share if you have code using JuMP or MOI for quantum information optimization!
