### ISSUE TITLE
Variable container in ComplexPlane

### ISSUE THREAD

**Issue by thinh-le** [jump-dev/ComplexOptInterface.jl#18]
Is it possible to create an n-by-m matrix variable (more generally any container) whose element are each in ComplexPlane()? Something like this:
```julia
y = @variable model y[1:3,1:5] in COI.ComplexPlane()
```

**Comment by odow** [comment]
This needs https://github.com/jump-dev/JuMP.jl/issues/2148

**Comment by odow** [comment]
Or it needs methods like

 * https://github.com/jump-dev/JuMP.jl/blob/bcb803ed32e422b6a3a72abd6dbc472264e3df63/src/macros.jl#L1555-L1561
 * https://github.com/jump-dev/JuMP.jl/blob/bcb803ed32e422b6a3a72abd6dbc472264e3df63/src/variables.jl#L1158-L1164

```julia
using JuMP
import ComplexOptInterface
const COI = ComplexOptInterface

function JuMP.build_variable(
    err::Function,
    variables::AbstractArray{<:JuMP.ScalarVariable},
    set::COI.ComplexPlane,
)
    return JuMP.build_variable.(err, variables, Ref(set))
end

function JuMP.add_variable(
    model::Model,
    variables::AbstractArray{<:COI.ComplexVariable},
    names::AbstractArray{<:String},
)
    return add_variable.(model, variables, names)
end

model = Model() 
@variable(model, y[i=1:3,j=1:5], set = COI.ComplexPlane())
```

**Comment by blegat** [comment]
Yes, that's another argument for https://github.com/jump-dev/JuMP.jl/issues/2148

**Comment by thinh-le** [comment]
Thanks, I'll leave it to you guys when to close this issue!
