### ISSUE TITLE
complex to real bridges (eg hermitian PSD constraints)

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/ComplexOptInterface.jl#4]
wanted to discuss whether this is feasible with the current design. I haven't seen a complex MOI model yet.

see https://docs.mosek.com/modeling-cookbook/sdo.html#hermitian-matrices for the transformation of a constraint from complex hermitian order-n cone to real PSD order-2n cone.

**Comment by odow** [comment]
Should this be transferred back to MOI?

Is it asking for `VectorAffineFunction{Complex{T}} -in- PSDCone` to be reformulated into VectorAffineFunction{T} -in- HermitianPSDCone`?

**Comment by blegat** [comment]
In that issue, I mention at the beginning the idea that the hermitian PSD set would be complex valued but we decided instead to use a higher dimension and it to be real valued as @chriscoey suggested. So the transformations mentioned in this issue are implemented in [`Constraint.HermitianToSymmetricPSDBridge`](https://jump.dev/MathOptInterface.jl/dev/submodules/Bridges/list_of_bridges/#MathOptInterface.Bridges.Constraint.HermitianToSymmetricPSDBridge), [`Variable.HermitianToSymmetricPSDBridge`](https://jump.dev/MathOptInterface.jl/dev/submodules/Bridges/list_of_bridges/#MathOptInterface.Bridges.Variable.HermitianToSymmetricPSDBridge) so this issue can be closed.
